### ISSUE TITLE
Redmine 3.0 compat?

### ISSUE THREAD

**Issue by AxisOfEval** [mikeploeger/redmine_timelog_timer#1]
Is this compatible with Redmine 3.0?

**Comment by janekska** [comment]
Looks like it is woking on my setup:

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_dashboard              2.5.0
  redmine_mail_reminder          3.0.0.0001
  redmine_theme_changer          0.2.0
  redmine_timelog_timer          2.0.1
  redmine_work_time              0.3.1

**Comment by mikeploeger** [comment]
Thank you for the test [janekska](https://github.com/janekska) 👌
